[package]
name = "leptos-modal-macros"
version = "0.3.0"
edition = "2024"
description = "Macros for leptos-modal"
license = "MIT or Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
